
#1.



In [28]:
#1.(a) Using a for loop, iterate through the list x and print an item if its divisible by 2 and less than 6
# e.g. "CEO: Apple, Name: Tim Cook" will be the third entry
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for i in x:
  if i<6 and i%2==0:
      print(i)

2
4


In [29]:
#1.(b) Using a for loop, iterate through the dictionary y and print a single string of the form "company, ceo"
y = {
'Satya Nadella': 'Microsoft',
'Jeff Bezos': 'Amazon',
'Tim Cook': 'Apple'
}
for key in y:
  print(key,",",y[key])


Satya Nadella , Microsoft
Jeff Bezos , Amazon
Tim Cook , Apple


#2.

In [30]:
# 2. Provided below are functions that are completely defined (add_numbers),
# partially defined (sub_numbers) and not defined (mult_numbers)
# (a) Complete sub_numbers so that it return difference of two numbers
def sub_numbers(a,b):
  return a-b
sub_numbers(4,5)

-1

In [31]:
# 2. (b) Write a function called mult_numbers to multiply two numbers
def mult_numbers(num1,num2):
  return num1*num2;
mult_numbers(3,4)

12

#3.


In [49]:
# 3.(a) Determine the shape, number of dimensions and type of
# elements in the numpy array arr
import numpy as np
arr= np.array([[3,4,5,9,16,25],[2,77,6,4,1,3]])

print(arr.shape)
print(arr.ndim)
print(type(arr))


(2, 6)
2
<class 'numpy.ndarray'>


In [33]:

# 3.(b) Determine the sum of elements in arr
np.sum(arr)



155

In [34]:
# 3.(c) Determine the mean of elements in arr
np.mean(arr)

12.916666666666666

In [35]:
# 3.(d) Create an array of the same shape as arr but filled with zeros
np.zeros_like(arr)


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [36]:
# 3.(e) Create an array of the same shape as arr but filled with ones
np.ones_like(arr)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [37]:
# 3.(f) Create an array of the same shape as arr but where all elements are squared values
np.square(arr)


array([[   9,   16,   25,   81,  256,  625],
       [   4, 5929,   36,   16,    1,    9]])

In [50]:
# 3.(g) Create an array result of shape 3*3 resulting from multiplication of arr with
np.dot(arr,arr.T)


array([[1012,  471],
       [ 471, 5995]])

#4.

In [54]:
# 4. The following piece of code creates a DataFrame

import pandas as pd
df = pd.read_csv('iris.csv')
df.head(10) #prints the first 10 rows.

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [40]:
# 4.(a) Determine the shape of the dataframe
df.shape

(150, 5)

In [41]:
# 4.(b) Print out all the columns of the dataframe
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [56]:
# 4.(c) Print the 3rd element of the dataframe
print(df.iloc[2])

sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object


In [62]:
# 4.(d) Find the average of 'petal_width' where species is 'virginica'
df.loc[df.species=='virginica']["petal_width"].mean()


2.026

In [66]:
# 4.(e) Find the maximum of 'sepal_width' where species is 'setosa'
df.loc[df.species=='setosa']["sepal_width"].max()


4.4

In [68]:
# 4.(f): What is the average value of sepal_length
df["sepal_length"].mean()

5.843333333333335

In [69]:
# 4.(g): What is the maximum value of sepal_width
df["sepal_width"].max()


4.4

In [70]:
# 4.(h): What is the minimum value of petal_width
df["petal_width"].min()

0.1